name: Generate Snake Animation

on:
  schedule:
    # Runs at 12:00 AM UTC every day
    - cron: "0 0 * * *"
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-20.04  # Runs in GitHub's Linux-based virtual environment
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Generate the Snake SVG
      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: ARMANANS1218
          outputs: dist

      # Step 3: Push the Snake SVG to a new branch
      - name: Push Snake Animation to GitHub
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          publish_branch: output
